version: '3'
services:
  mysql:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: vova
      MYSQL_DATABASE: eng
      MYSQL_USER: vova
      MYSQL_PASSWORD: vova
    ports:
      - "${MYSQL_PORT}:3306"
    tty: true
    volumes:
      - "./db:/var/lib/mysql:cached"